name: Daily Market Report

on:
  schedule:
    - cron: '0 2 * * *'   # 每天 UTC 2:00 运行，相当于北京时间 10:00
  workflow_dispatch:       # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run market report
      env:
        SERVER_CHAN_KEY: ${{ secrets.SERVER_CHAN_KEY }}
      run: |
        python market_report.py

    - name: Commit log files
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add market_log.csv alerts.json || true
        git commit -m "Update market log" || echo "No changes to commit"
        git push
        
    - name: Debug Python output
      run: |
        echo "Check Python version:"
        python --version
        echo "List files:"
        ls -l
        echo "Check logs:"
        cat market_log.csv || echo "No market_log.csv"

